services:
  - type: web
    name: nexgensis-backend
    env: docker
    repo: https://github.com/Tusha8010/nexgensis-devops-assignment.git
    dockerfilePath: backend/Dockerfile
    branch: main
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000

  - type: web
    name: nexgensis-frontend
    env: docker
    repo: https://github.com/Tusha8010/nexgensis-devops-assignment.git
    dockerfilePath: frontend/Dockerfile
    branch: main
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 80

