services:
  - type: web
    name: nexgensis-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    autoDeploy: true
    healthCheckPath: /api/status/

  - type: web
    name: nexgensis-frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    autoDeploy: true
